AAE-29362 Test Query service

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -129,169 +129,169 @@ jobs:
         run: make docker/activiti-cloud-identity-adapter
 
 
-  acceptance-tests:
-    runs-on: ubuntu-latest
-    needs: build
-    env:
-      MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
-    strategy:
-      # avoid overloading test cluster
-      max-parallel: 2
-      fail-fast: true
-      matrix:
-        messaging-broker: [ rabbitmq, kafka ]
-        messaging-partitioned: [ partitioned, non-partitioned ]
-        messaging-destinations: [ default-destinations ]
-        include:
-          - messaging-broker: kafka
-            messaging-partitioned: partitioned
-            messaging-destinations: override-destinations
-          - messaging-broker: rabbitmq
-            messaging-partitioned: non-partitioned
-            messaging-destinations: pdb
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-
-      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-
-      - name: Setup Java JDK 21
-        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # 4.7.0
-        with:
-          java-version: 21
-          distribution: 'temurin'
-
-      - name: Set up kubectl
-        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v3
-        with:
-          version: v1.19.6
-
-      - name: Set up Helm
-        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v3
-        with:
-          version: v3.5.2
-
-      - name: Set up rancher
-        uses: Alfresco/alfresco-build-tools/.github/actions/setup-rancher-cli@695272dc5144fc5484e4ea610ae82715fb6294c8 # v8.14.1
-        with:
-          url: ${{ secrets.RANCHER2_URL }}
-          access-key: ${{ secrets.RANCHER2_ACCESS_KEY }}
-          secret-key: ${{ secrets.RANCHER2_SECRET_KEY }}
-          context: ${{ env.CLUSTER_NAME }}
-
-      - uses: ./.github/actions/setup-env-for-broker
-        with:
-          messaging-broker: ${{ matrix.messaging-broker }}
-          messaging-partitioning-option: ${{ matrix.messaging-partitioned }}
-          messaging-destinations-option: ${{ matrix.messaging-destinations }}
-          version: ${{ needs.build.outputs.version }}
-
-      - name: Delete preview for ${{ matrix.messaging-broker }}
-        if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'preview') }}
-        run: |
-          kubectl delete ns $PREVIEW_NAME || true
-
-      - name: Install release for ${{ matrix.messaging-broker }}
-        run: |
-          ### Variables ###
-          export SSO_PROTOCOL=https
-          export GATEWAY_PROTOCOL=https
-          export GLOBAL_GATEWAY_DOMAIN=$CLUSTER_NAME.$CLUSTER_DOMAIN
-          export GATEWAY_HOST=gateway-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
-          export SSO_HOST=identity-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
-
-          ### Main ###
-
-          echo "Installing release with make install"
-          make install
-
-      - name: (kafka,partitioned) Checks that consumers can be a different number from partitions
-        if: ${{ matrix.messaging-broker == 'kafka' && matrix.messaging-partitioned == 'partitioned' && matrix.messaging-destinations == 'default-destinations' }}
-        run: |
-          ### Variables ###
-          export SSO_PROTOCOL=https
-          export GATEWAY_PROTOCOL=https
-          export GLOBAL_GATEWAY_DOMAIN=$CLUSTER_NAME.$CLUSTER_DOMAIN
-          export GATEWAY_HOST=gateway-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
-          export SSO_HOST=identity-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
-          export QUERY_CONSUMER_NUMBER=2
-
-          ### Functions ###
-
-          # It checks that the RESULT env var is equals to the first
-          # argument passed to the function
-          #
-          check_result_is () {
-            if [ "$RESULT" == "$1" ]; then
-              echo "correct"
-            else
-              echo "number expected is $1 but result is $RESULT"
-              exit 1
-            fi
-          }
-
-          # It counts the number of query consumer pods in the
-          # cluster and set it in RESULT env var
-          #
-          count_query_consumer_pods () {
-            export RESULT=$(kubectl -n $PREVIEW_NAME get pods -o \
-              'custom-columns=POD:metadata.name,READY-true:status.containerStatuses[*].ready' |\
-              grep -e 'activiti-cloud-query.*true' | wc -l | xargs);
-          }
-
-          # It counts the number of query partition of engineEvents topic
-          # created in Kafka and set it in RESULT env var
-          #
-          count_query_topic_partitions () {
-            export RESULT=$(kubectl exec -t -n $PREVIEW_NAME kafka-0 \
-              -c kafka "--" sh -c $'/opt/bitnami/kafka/bin/kafka-topics.sh \
-              --bootstrap-server=localhost:9092 --describe \
-              --topic engineEvents | grep PartitionCount |\
-              awk \'{ printf "%s",$6 }\'')
-          }
-
-          ### Main ###
-
-          echo "It checks the deployment has 1 query pod consumer"
-          count_query_consumer_pods
-          check_result_is 1
-
-          echo "It checks the deployment has 4 query topic patitions"
-          count_query_topic_partitions
-          check_result_is 4
-
-      - uses: ./.github/actions/check-service-health
-        with:
-          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/identity-adapter-service/actuator/health
-
-      - name: Run Identity Adapter Acceptance Tests
-        # identity adapter acceptance tests does not depend on messaging, so they can be run only once
-        if: ${{ matrix.messaging-broker == 'rabbitmq' && matrix.messaging-partitioned == 'non-partitioned' && matrix.messaging-destinations == 'default-destinations' }}
-        run: |
-          make test/identity-adapter-acceptance-tests
-
-      - uses: ./.github/actions/check-service-health
-        with:
-          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/rb/actuator/health
-
-      - uses: ./.github/actions/check-service-health
-        with:
-          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/query/actuator/health
-
-      - name: Run Acceptance Tests for ${{ matrix.messaging-broker }}
-        run: |
-          make test/runtime-acceptance-tests
-
-      - name: Delete Helm chart for ${{ matrix.messaging-broker }}
-        if: always()
-        run: |
-          echo "Delete Helm release"
-          make delete
+#  acceptance-tests:
+#    runs-on: ubuntu-latest
+#    needs: build
+#    env:
+#      MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
+#    strategy:
+#      # avoid overloading test cluster
+#      max-parallel: 2
+#      fail-fast: true
+#      matrix:
+#        messaging-broker: [ rabbitmq, kafka ]
+#        messaging-partitioned: [ partitioned, non-partitioned ]
+#        messaging-destinations: [ default-destinations ]
+#        include:
+#          - messaging-broker: kafka
+#            messaging-partitioned: partitioned
+#            messaging-destinations: override-destinations
+#          - messaging-broker: rabbitmq
+#            messaging-partitioned: non-partitioned
+#            messaging-destinations: pdb
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+#
+#      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#
+#      - name: Setup Java JDK 21
+#        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # 4.7.0
+#        with:
+#          java-version: 21
+#          distribution: 'temurin'
+#
+#      - name: Set up kubectl
+#        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v3
+#        with:
+#          version: v1.19.6
+#
+#      - name: Set up Helm
+#        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v3
+#        with:
+#          version: v3.5.2
+#
+#      - name: Set up rancher
+#        uses: Alfresco/alfresco-build-tools/.github/actions/setup-rancher-cli@695272dc5144fc5484e4ea610ae82715fb6294c8 # v8.14.1
+#        with:
+#          url: ${{ secrets.RANCHER2_URL }}
+#          access-key: ${{ secrets.RANCHER2_ACCESS_KEY }}
+#          secret-key: ${{ secrets.RANCHER2_SECRET_KEY }}
+#          context: ${{ env.CLUSTER_NAME }}
+#
+#      - uses: ./.github/actions/setup-env-for-broker
+#        with:
+#          messaging-broker: ${{ matrix.messaging-broker }}
+#          messaging-partitioning-option: ${{ matrix.messaging-partitioned }}
+#          messaging-destinations-option: ${{ matrix.messaging-destinations }}
+#          version: ${{ needs.build.outputs.version }}
+#
+#      - name: Delete preview for ${{ matrix.messaging-broker }}
+#        if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'preview') }}
+#        run: |
+#          kubectl delete ns $PREVIEW_NAME || true
+#
+#      - name: Install release for ${{ matrix.messaging-broker }}
+#        run: |
+#          ### Variables ###
+#          export SSO_PROTOCOL=https
+#          export GATEWAY_PROTOCOL=https
+#          export GLOBAL_GATEWAY_DOMAIN=$CLUSTER_NAME.$CLUSTER_DOMAIN
+#          export GATEWAY_HOST=gateway-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
+#          export SSO_HOST=identity-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
+#
+#          ### Main ###
+#
+#          echo "Installing release with make install"
+#          make install
+#
+#      - name: (kafka,partitioned) Checks that consumers can be a different number from partitions
+#        if: ${{ matrix.messaging-broker == 'kafka' && matrix.messaging-partitioned == 'partitioned' && matrix.messaging-destinations == 'default-destinations' }}
+#        run: |
+#          ### Variables ###
+#          export SSO_PROTOCOL=https
+#          export GATEWAY_PROTOCOL=https
+#          export GLOBAL_GATEWAY_DOMAIN=$CLUSTER_NAME.$CLUSTER_DOMAIN
+#          export GATEWAY_HOST=gateway-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
+#          export SSO_HOST=identity-$PREVIEW_NAME.$GLOBAL_GATEWAY_DOMAIN
+#          export QUERY_CONSUMER_NUMBER=2
+#
+#          ### Functions ###
+#
+#          # It checks that the RESULT env var is equals to the first
+#          # argument passed to the function
+#          #
+#          check_result_is () {
+#            if [ "$RESULT" == "$1" ]; then
+#              echo "correct"
+#            else
+#              echo "number expected is $1 but result is $RESULT"
+#              exit 1
+#            fi
+#          }
+#
+#          # It counts the number of query consumer pods in the
+#          # cluster and set it in RESULT env var
+#          #
+#          count_query_consumer_pods () {
+#            export RESULT=$(kubectl -n $PREVIEW_NAME get pods -o \
+#              'custom-columns=POD:metadata.name,READY-true:status.containerStatuses[*].ready' |\
+#              grep -e 'activiti-cloud-query.*true' | wc -l | xargs);
+#          }
+#
+#          # It counts the number of query partition of engineEvents topic
+#          # created in Kafka and set it in RESULT env var
+#          #
+#          count_query_topic_partitions () {
+#            export RESULT=$(kubectl exec -t -n $PREVIEW_NAME kafka-0 \
+#              -c kafka "--" sh -c $'/opt/bitnami/kafka/bin/kafka-topics.sh \
+#              --bootstrap-server=localhost:9092 --describe \
+#              --topic engineEvents | grep PartitionCount |\
+#              awk \'{ printf "%s",$6 }\'')
+#          }
+#
+#          ### Main ###
+#
+#          echo "It checks the deployment has 1 query pod consumer"
+#          count_query_consumer_pods
+#          check_result_is 1
+#
+#          echo "It checks the deployment has 4 query topic patitions"
+#          count_query_topic_partitions
+#          check_result_is 4
+#
+#      - uses: ./.github/actions/check-service-health
+#        with:
+#          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/identity-adapter-service/actuator/health
+#
+#      - name: Run Identity Adapter Acceptance Tests
+#        # identity adapter acceptance tests does not depend on messaging, so they can be run only once
+#        if: ${{ matrix.messaging-broker == 'rabbitmq' && matrix.messaging-partitioned == 'non-partitioned' && matrix.messaging-destinations == 'default-destinations' }}
+#        run: |
+#          make test/identity-adapter-acceptance-tests
+#
+#      - uses: ./.github/actions/check-service-health
+#        with:
+#          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/rb/actuator/health
+#
+#      - uses: ./.github/actions/check-service-health
+#        with:
+#          health-url: ${{ env.GATEWAY_PROTOCOL }}://${{ env.GATEWAY_HOST }}/query/actuator/health
+#
+#      - name: Run Acceptance Tests for ${{ matrix.messaging-broker }}
+#        run: |
+#          make test/runtime-acceptance-tests
+#
+#      - name: Delete Helm chart for ${{ matrix.messaging-broker }}
+#        if: always()
+#        run: |
+#          echo "Delete Helm release"
+#          make delete
 
   delete-test-images:
     runs-on: ubuntu-latest
